tracing: add missing tracing top function k_thread_wakeup
to fix build error "undefined reference to `sys_trace_k_thread_wakeup'"

Signed-off-by: Dong Wang <dong.d.wang@intel.com>